[package]
name = "common-macros"
description = "Macros for common crates."
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0.36"
syn = "2.0.70"

[features]
tracing = []
